spring.application.name=system-async-kafka-migrate-redpanda
spring.profiles.active=test
spring.data.mongodb.uri=mongodb://localhost:27017/testdb
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.auto-offset-reset=earliest
